CREATE TABLE IF NOT EXISTS DIM_DATE AS (
    WITH DATE_SEQ AS (
        SELECT DATEADD(DAY, SEQ4(), '2017-01-01') AS MY_DATE
        FROM TABLE(GENERATOR(ROWCOUNT => 4000))
    )

    SELECT
        TO_DATE(MY_DATE) AS FORECAST_DATE
        , TO_TIMESTAMP(MY_DATE) AS DATETIME
        , YEAR(MY_DATE) AS YEAR
        , MONTH(MY_DATE) AS MONTH
        , MONTHNAME(MY_DATE) AS MONTHNAME
        , DAY(MY_DATE) AS DAY
        , DAYOFWEEK(MY_DATE) AS DAYOFWEEK
        , WEEKOFYEAR(MY_DATE) AS WEEKOFYEAR
        , DAYOFYEAR(MY_DATE) AS DAYOFYEAR
    FROM DATE_SEQ
);
