--requires ACCOUNTADMIN privileges
USE ROLE ACCOUNTADMIN;

SELECT
    TABLE_CATALOG
    , TABLE_NAME
    , ((ACTIVE_BYTES / 1024) / 1024) / 1024 AS STORAGE_USAGE_GB
FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
ORDER BY STORAGE_USAGE_GB DESC;
