USE ROLE HOTELS_DEV_OWNER;
USE WAREHOUSE DEVELOPER_WH;
USE DATABASE HOTELS_DEV;
USE SCHEMA UTILITIES;

CREATE TABLE DATA_RECONCILIATION(
	SRC_DB VARCHAR(50) NOT NULL,
	TABLE_NAME	VARCHAR(100) NOT NULL,
	SRC_TBL_COUNT NUMBER(38,0) NOT NULL,
	TARGET_TBL_COUNT NUMBER(38,0) NOT NULL,
	MATCH_COMPARISON VARCHAR(12) NOT NULL,
	QUERY_COMPARISON_TS DATETIME NOT NULL
)
;

CREATE OR REPLACE TABLE DATA_RECONCILIATION (   SRC_DB VARCHAR(50) NOT NULL,   TABLE_NAME	VARCHAR(100) NOT NULL,   SRC_TBL_COUNT NUMBER(38,0) NOT NULL,   TARGET_TBL_COUNT NUMBER(38,0) NOT NULL,   MATCH_COMPARISON VARCHAR(12) NOT NULL,   QUERY_COMPARISON_TS DATETIME NOT NULL );